[template]
src = "ng-proxy.tmpl"
dest = "/etc/nginx/conf.d/ng-proxy.conf"
keys = [ "/registry/services/specs/" ]
owner = "root"
mode = "0644"

check_cmd = "/usr/sbin/nginx -t"
reload_cmd = "kill `cat /run/nginx.pid`; /usr/sbin/nginx"
